name: default
create_nuggets: true
create_qrels: true
judge: true
llm_model: openai/gpt-oss-120b
timestamp: '2026-02-05T17:51:01.029194+00:00'
git:
  commit: 6a7bf89e4b3229f8edd2dbf8c17216d16d3ee5ed
  dirty: 'true'
  remote: git@github.com:trec-auto-judge/auto-judge-starter-kit.git
settings:
  filebase: '{_name}'
nugget_settings:
  filebase: '{_name}'
  questions_per_topic: 3
judge_settings:
  filebase: '{_name}'
  keyword_bonus: 0.2
  on_missing_evals: fix_aggregate
qrels_settings:
  filebase: '{_name}'
  grade_range:
  - 0
  - 3
  length_threshold: 100
